#pragma once

#define DEBOUNCE 5

#define SPLIT_USB_DETECT
// #define SOFT_SERIAL_PIN GP1
// #define SPLIT_TRANSPORT_MIRROR
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000

//#define SPLIT_LED_STATE_ENABLE
//#define RGB_MATRIX_LED_COUNT 68

#define SERIAL_USART_FULL_DUPLEX 
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
